/* interface.h : Impala interface file generated by impala */
#ifndef INTERFACE_H
#define INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

struct Vec3 {
    float x;
    float y;
    float z;
};

struct BBox {
    struct Vec3 min;
    struct Vec3 max;
};

struct Node {
    struct BBox left_bb;
    struct BBox right_bb;
    int right;
    int left;
    int pad0;
    int pad1;
};

struct Ray {
    struct Vec3 org;
    float tmin;
    struct Vec3 dir;
    float tmax;
};

struct Hit {
    int tri_id;
    float tmax;
    int pad0;
    int pad1;
};

void traverse_accel(struct Node* nodes_ptr, struct Ray* rays_ptr, struct Vec3* tris_ptr, struct Hit* hits_ptr, int ray_count);

#ifdef __cplusplus
}
#endif

#endif /* INTERFACE_H */

