/* grid.h : Impala interface file generated by impala */
#ifndef GRID_H
#define GRID_H

#ifdef __cplusplus
extern "C" {
#endif

struct Cell {
    int begin;
    int end;
};

struct Vec3i {
    int x;
    int y;
    int z;
};

struct Vec3f {
    float x;
    float y;
    float z;
};

struct Tri {
    struct Vec3f v0;
    float nx;
    struct Vec3f e1;
    float ny;
    struct Vec3f e2;
    float nz;
};

struct Ray {
    struct Vec3f org;
    float tmin;
    struct Vec3f dir;
    float tmax;
};

struct Hit {
    int tri_id;
    float t;
    float u;
    float v;
};

void traverse_grid_gpu(struct Cell* cells, struct Vec3i* dims, struct Vec3f* min, struct Vec3f* max, struct Tri* tris, struct Ray* rays, struct Hit* hits, int ray_count);

#ifdef __cplusplus
}
#endif

#endif /* GRID_H */

